######################################################################
# Automatically generated by qmake (3.1) Tue Mar 9 16:38:42 2021
######################################################################

TEMPLATE = app
TARGET = mqtt_test
INCLUDEPATH += .
CONFIG -=qt

# The following define makes your compiler warn you if you use any
# feature of Qt which has been marked as deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

# You can also make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0
QMAKE_CXXFLAGS += -std=c++11
# Input
SOURCES += main.cpp \
    ../MQTT_C/mqtt.c \
    ../MQTT_C/mqtt_pal.c \
    ../mqtt_client.cpp

HEADERS += \
    ../MQTT_C/mqtt.h \
    ../MQTT_C/mqtt_pal.h \
    ../mqtt_client.h

INCLUDEPATH += ../

LIBS += -lpthread


DISTFILES +=
